# SQL Server 连接配置
jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=Online_SMSystem4SP;trustServerCertificate=true
jdbc.username=yyt
jdbc.password=231002110

# /**
#  *　　　　　　　　┏┓　　　┏┓+ +
#  *　　　　　　　┏┛┻━━━┛┻┓ + +
#  *　　　　　　　┃　　　　　　　┃
#  *　　　　　　　┃　　　━　　　┃ ++ + + +
#  *　　　　　　 ████━████ ┃+
#  *　　　　　　　┃　　　　　　　┃ +
#  *　　　　　　　┃　　　┻　　　┃
#  *　　　　　　　┃　　　　　　　┃ + +
#  *　　　　　　　┗━┓　　　┏━┛
#  *　　　　　　　　　┃　　　┃
#  *　　　　　　　　　┃　　　┃ + + + +
#  *　　　　　　　　　┃　　　┃　　　　Code is far away from bug with the animal protecting
#  *　　　　　　　　　┃　　　┃ + 　　　　神兽保佑,代码无bug
#  *　　　　　　　　　┃　　　┃
#  *　　　　　　　　　┃　　　┃　　+
#  *　　　　　　　　　┃　 　　┗━━━┓ + +
#  *　　　　　　　　　┃ 　　　　　　　┣┓
#  *　　　　　　　　　┃ 　　　　　　　┏┛
#  *　　　　　　　　　┗┓┓┏━┳┓┏┛ + + + +
#  *　　　　　　　　　　┃┫┫　┃┫┫
#  *　　　　　　　　　　┗┻┛　┗┻┛+ + + +
#  */
