smtp.enabled=true

smtp.host=smtp.qq.com
smtp.port=465

smtp.username=1637389187@qq.com
smtp.password=kndidxkbozrojijf

smtp.from=1637389187@qq.com
smtp.fromName=OnlineSM_system

smtp.starttls=false
smtp.ssl=true

app.baseUrl=http://localhost:2008/Online_SMsystem4SP

smtp.debug=true

mail.autoRemind.overdueDays=7
mail.autoRemind.minIntervalDays=7
mail.autoRemind.maxPerRun=50

# /**
#  *　　　　　　　　┏┓　　　┏┓+ +
#  *　　　　　　　┏┛┻━━━┛┻┓ + +
#  *　　　　　　　┃　　　　　　　┃
#  *　　　　　　　┃　　　━　　　┃ ++ + + +
#  *　　　　　　 ████━████ ┃+
#  *　　　　　　　┃　　　　　　　┃ +
#  *　　　　　　　┃　　　┻　　　┃
#  *　　　　　　　┃　　　　　　　┃ + +
#  *　　　　　　　┗━┓　　　┏━┛
#  *　　　　　　　　　┃　　　┃
#  *　　　　　　　　　┃　　　┃ + + + +
#  *　　　　　　　　　┃　　　┃　　　　Code is far away from bug with the animal protecting
#  *　　　　　　　　　┃　　　┃ + 　　　　神兽保佑,代码无bug
#  *　　　　　　　　　┃　　　┃
#  *　　　　　　　　　┃　　　┃　　+
#  *　　　　　　　　　┃　 　　┗━━━┓ + +
#  *　　　　　　　　　┃ 　　　　　　　┣┓
#  *　　　　　　　　　┃ 　　　　　　　┏┛
#  *　　　　　　　　　┗┓┓┏━┳┓┏┛ + + + +
#  *　　　　　　　　　　┃┫┫　┃┫┫
#  *　　　　　　　　　　┗┻┛　┗┻┛+ + + +
#  */
