upload.baseDir=D:/upload
upload.avatarSubDir=avatars
upload.resumeSubDir=resumes
upload.legacyProfileDir=profile

# /**
#  *　　　　　　　　┏┓　　　┏┓+ +
#  *　　　　　　　┏┛┻━━━┛┻┓ + +
#  *　　　　　　　┃　　　　　　　┃
#  *　　　　　　　┃　　　━　　　┃ ++ + + +
#  *　　　　　　 ████━████ ┃+
#  *　　　　　　　┃　　　　　　　┃ +
#  *　　　　　　　┃　　　┻　　　┃
#  *　　　　　　　┃　　　　　　　┃ + +
#  *　　　　　　　┗━┓　　　┏━┛
#  *　　　　　　　　　┃　　　┃
#  *　　　　　　　　　┃　　　┃ + + + +
#  *　　　　　　　　　┃　　　┃　　　　Code is far away from bug with the animal protecting
#  *　　　　　　　　　┃　　　┃ + 　　　　神兽保佑,代码无bug
#  *　　　　　　　　　┃　　　┃
#  *　　　　　　　　　┃　　　┃　　+
#  *　　　　　　　　　┃　 　　┗━━━┓ + +
#  *　　　　　　　　　┃ 　　　　　　　┣┓
#  *　　　　　　　　　┃ 　　　　　　　┏┛
#  *　　　　　　　　　┗┓┓┏━┳┓┏┛ + + + +
#  *　　　　　　　　　　┃┫┫　┃┫┫
#  *　　　　　　　　　　┗┻┛　┗┻┛+ + + +
#  */
